# Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding
# the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.


def even_fib(num):
    if type(num) != int:
        return 'Input must be Integer'
    elif num < 0:
        return 'Number must be positive'
    x = 1
    y = 1
    z = 0
    result = 0
    while z < num:
        z = (x + y)
        if z % 2 == 0:
            result += z
        x, y = y, z
    return result


print(even_fib(4000000))
